#!/bin/sh

# Dependencies:
# convert wal xdotool magick awww

wall_dir=~/pix/wall

if [ -z "$1" ]; then
  wall="$(find "$wall_dir" -type f -name "*.jpg" -o -name "*.png" | shuf -n1)"
else
  wall="$1"
fi

magick "$wall" ~/.local/share/bg.jpg
awww img ~/.local/share/bg.jpg
wal -c
wal -i ~/.local/share/bg.jpg
xdotool key super+F5
cp ~/.cache/wal/colors-kitty.conf ~/.config/kitty/theme.conf
cp ~/.cache/wal/colors-rofi-light.rasi ~/.config/rofi/themes/mg_girl.rasi
